/**
 * Provider for SEC/EDGAR historical fundamentals data.
 * Reads static JSON files from public/data/sec/ generated by stock-scanner-data.
 */

import { promises as fs } from "fs";
import path from "path";

import type { SecIndex, SecTickerData } from "@/lib/types/sec-fundamentals";

const SEC_DATA_DIR = path.join(process.cwd(), "public", "data", "sec");

let cachedIndex: SecIndex | null = null;

/** Reset the in-memory index cache (used in tests). */
export function resetCache(): void {
  cachedIndex = null;
}

async function loadIndex(): Promise<SecIndex | null> {
  if (cachedIndex !== null) {
    return cachedIndex;
  }
  try {
    const raw = await fs.readFile(
      path.join(SEC_DATA_DIR, "_index.json"),
      "utf-8"
    );
    cachedIndex = JSON.parse(raw) as SecIndex;
    return cachedIndex;
  } catch {
    return null;
  }
}

export async function hasSecData(ticker: string): Promise<boolean> {
  const index = await loadIndex();
  if (index === null) {
    return false;
  }
  return index.tickers.includes(ticker.toUpperCase());
}

export async function getSecHistory(
  ticker: string
): Promise<SecTickerData | null> {
  const normalizedTicker = ticker.toUpperCase();
  const hasData = await hasSecData(normalizedTicker);
  if (!hasData) {
    return null;
  }

  try {
    const filePath = path.join(SEC_DATA_DIR, `${normalizedTicker}.json`);
    const raw = await fs.readFile(filePath, "utf-8");
    return JSON.parse(raw) as SecTickerData;
  } catch {
    return null;
  }
}

export async function getAvailableTickers(): Promise<readonly string[]> {
  const index = await loadIndex();
  if (index === null) {
    return [];
  }
  return index.tickers;
}
