/**
 * Provider for SEC/EDGAR historical fundamentals data.
 * Reads static JSON files from public/data/sec/ generated by stock-scanner-data.
 */

import { promises as fs } from "fs";
import path from "path";

import type { SecIndex, SecTickerData } from "@/lib/types/sec-fundamentals";

const SEC_DATA_DIR = path.join(process.cwd(), "public", "data", "sec");

let cachedIndex: SecIndex | null = null;
const tickerCache = new Map<string, SecTickerData>();
let allLoaded = false;

/** Reset the in-memory index cache (used in tests). */
export function resetCache(): void {
  cachedIndex = null;
  tickerCache.clear();
  allLoaded = false;
}

async function loadIndex(): Promise<SecIndex | null> {
  if (cachedIndex !== null) {
    return cachedIndex;
  }
  try {
    const raw = await fs.readFile(
      path.join(SEC_DATA_DIR, "_index.json"),
      "utf-8"
    );
    cachedIndex = JSON.parse(raw) as SecIndex;
    return cachedIndex;
  } catch {
    return null;
  }
}

export async function hasSecData(ticker: string): Promise<boolean> {
  const index = await loadIndex();
  if (index === null) {
    return false;
  }
  return index.tickers.includes(ticker.toUpperCase());
}

export async function getSecHistory(
  ticker: string
): Promise<SecTickerData | null> {
  const normalizedTicker = ticker.toUpperCase();

  // Serve from memory cache if available
  const cached = tickerCache.get(normalizedTicker);
  if (cached) return cached;
  if (allLoaded) return null; // Already loaded everything, ticker not found

  const hasData = await hasSecData(normalizedTicker);
  if (!hasData) {
    return null;
  }

  try {
    const filePath = path.join(SEC_DATA_DIR, `${normalizedTicker}.json`);
    const raw = await fs.readFile(filePath, "utf-8");
    const data = JSON.parse(raw) as SecTickerData;
    tickerCache.set(normalizedTicker, data);
    return data;
  } catch {
    return null;
  }
}

/**
 * Pre-load all SEC data into memory for fast lookups.
 * Call once before batch-fetching stocks to avoid per-ticker I/O.
 */
export async function preloadSecData(): Promise<void> {
  if (allLoaded) return;
  const index = await loadIndex();
  if (!index) { allLoaded = true; return; }

  const results = await Promise.allSettled(
    index.tickers.map(async (ticker) => {
      try {
        const filePath = path.join(SEC_DATA_DIR, `${ticker}.json`);
        const raw = await fs.readFile(filePath, "utf-8");
        tickerCache.set(ticker, JSON.parse(raw) as SecTickerData);
      } catch { /* skip unreadable files */ }
    })
  );
  allLoaded = true;
}

export async function getAvailableTickers(): Promise<readonly string[]> {
  const index = await loadIndex();
  if (index === null) {
    return [];
  }
  return index.tickers;
}
