/**
 * Provider for SEC/EDGAR historical fundamentals data.
 * Reads static JSON files from public/data/sec/ generated by stock-scanner-data.
 *
 * Caching: the index and per-ticker data are cached in memory with a TTL.
 * After a data refresh (npm run refresh), the cache expires automatically
 * within INDEX_TTL_MS — no server restart required.
 */

import { promises as fs } from "fs";
import path from "path";

import type { SecIndex, SecTickerData } from "@/lib/types/sec-fundamentals";

const SEC_DATA_DIR = path.join(process.cwd(), "public", "data", "sec");

/** Index cache TTL: 5 minutes in production, instant in tests. */
const INDEX_TTL_MS = process.env.NODE_ENV === "test" ? 0 : 5 * 60 * 1000;

/** Per-ticker cache TTL: 30 minutes. */
const TICKER_TTL_MS = 30 * 60 * 1000;

interface CachedItem<T> {
  data: T;
  loadedAt: number;
}

let cachedIndex: CachedItem<SecIndex> | null = null;
const tickerCache = new Map<string, CachedItem<SecTickerData>>();
let allLoaded = false;
let allLoadedAt = 0;

/**
 * Convert Yahoo-style ticker (BRK-B) to SEC-style (BRK.B) and vice-versa.
 * SEC EDGAR uses dots, Yahoo Finance uses dashes for multi-class tickers.
 */
function yahooToSec(ticker: string): string {
  return ticker.replace(/-/g, ".");
}

function isStale<T>(item: CachedItem<T> | null, ttlMs: number): boolean {
  if (item === null) return true;
  return Date.now() - item.loadedAt > ttlMs;
}

/** Reset the in-memory caches (used in tests). */
export function resetCache(): void {
  cachedIndex = null;
  tickerCache.clear();
  allLoaded = false;
  allLoadedAt = 0;
}

async function loadIndex(): Promise<SecIndex | null> {
  if (cachedIndex !== null && !isStale(cachedIndex, INDEX_TTL_MS)) {
    return cachedIndex.data;
  }
  try {
    const raw = await fs.readFile(
      path.join(SEC_DATA_DIR, "_index.json"),
      "utf-8"
    );
    const data = JSON.parse(raw) as SecIndex;
    cachedIndex = { data, loadedAt: Date.now() };
    return data;
  } catch {
    return null;
  }
}

export async function hasSecData(ticker: string): Promise<boolean> {
  const index = await loadIndex();
  if (index === null) {
    return false;
  }
  const secTicker = yahooToSec(ticker.toUpperCase());
  return index.tickers.includes(secTicker);
}

export async function getSecHistory(
  ticker: string
): Promise<SecTickerData | null> {
  const secTicker = yahooToSec(ticker.toUpperCase());

  // Serve from memory cache if available and fresh
  const cached = tickerCache.get(secTicker);
  if (cached && !isStale(cached, TICKER_TTL_MS)) return cached.data;

  // If everything was preloaded recently, a miss means the ticker doesn't exist
  if (allLoaded && Date.now() - allLoadedAt < TICKER_TTL_MS) return null;

  const hasData = await hasSecData(ticker);
  if (!hasData) {
    return null;
  }

  try {
    const filePath = path.join(SEC_DATA_DIR, `${secTicker}.json`);
    const raw = await fs.readFile(filePath, "utf-8");
    const data = JSON.parse(raw) as SecTickerData;
    tickerCache.set(secTicker, { data, loadedAt: Date.now() });
    return data;
  } catch {
    return null;
  }
}

/**
 * Pre-load all SEC data into memory for fast lookups.
 * Call once before batch-fetching stocks to avoid per-ticker I/O.
 */
export async function preloadSecData(): Promise<void> {
  if (allLoaded && Date.now() - allLoadedAt < TICKER_TTL_MS) return;
  const index = await loadIndex();
  if (!index) { allLoaded = true; allLoadedAt = Date.now(); return; }

  await Promise.allSettled(
    index.tickers.map(async (ticker) => {
      try {
        const filePath = path.join(SEC_DATA_DIR, `${ticker}.json`);
        const raw = await fs.readFile(filePath, "utf-8");
        tickerCache.set(ticker, { data: JSON.parse(raw) as SecTickerData, loadedAt: Date.now() });
      } catch { /* skip unreadable files */ }
    })
  );
  allLoaded = true;
  allLoadedAt = Date.now();
}

export async function getAvailableTickers(): Promise<readonly string[]> {
  const index = await loadIndex();
  if (index === null) {
    return [];
  }
  return index.tickers;
}
